### ISSUE TITLE
Bug: crashes if body is just a number

### ISSUE THREAD

**Issue by vesse** [jamonkko/console-log-server#8]
```
npx console-log-server -p 3000 -b "123123123"
```

leads to 

```
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 123123123
    at ServerResponse.writeHead (node:_http_server:351:11)
    at ServerResponse._implicitHeader (node:_http_server:337:8)
    at ServerResponse.end (node:_http_outgoing:1068:10)
    at ServerResponse.send (/Users/me/.npm/_npx/2467e008c9c3aefd/node_modules/express/lib/response.js:232:10)
    at defaultRoute (/Users/me/.npm/_npx/2467e008c9c3aefd/node_modules/console-log-server/dist/index.js:99:35)
    at Layer.handle [as handle_request] (/Users/me/.npm/_npx/2467e008c9c3aefd/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/me/.npm/_npx/2467e008c9c3aefd/node_modules/express/lib/router/route.js:149:13)
    at next (/Users/me/.npm/_npx/2467e008c9c3aefd/node_modules/express/lib/router/route.js:145:7)
    at next (/Users/me/.npm/_npx/2467e008c9c3aefd/node_modules/express/lib/router/route.js:145:7)
    at next (/Users/me/.npm/_npx/2467e008c9c3aefd/node_modules/express/lib/router/route.js:145:7)
```

**Comment by jamonkko** [comment]
Fix is in #9 

Now just need to check if I can get this released :)
